INVALID_MODE = "INVALID_MODE"

INVALID_INPUT_KIND = "INVALID_INPUT_KIND"

INVALID_REQUEST = "INVALID_REQUEST"


EMPTY_INPUT = "EMPTY_INPUT"

INVALID_BASE64 = "INVALID_BASE64"


INTERNAL_ERROR = "INTERNAL_ERROR"
